env:
  browser: false
  es2021: true
  node: true    
extends:
  - airbnb-base
  - airbnb-typescript/base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  no-unused-vars: 0
  class-methods-use-this: 0
  no-console: 0